name: Baby Olson
favicon: null
layout_spectrum: 0.49703
typography_spectrum: 0.07207
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3125
  lightness: 0.9022674150764942
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
